""" 

Revision ID: 21ae6c934e09
Revises: 9c10477d3030
Create Date: 2024-04-22 10:23:51.699799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ae6c934e09'
down_revision: Union[str, None] = '9c10477d3030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscribed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscribed_id'], ['users.id'], name='subscriptions_subscribed_id_fkey'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], name='subscriptions_subscriber_id_fkey'),
    sa.UniqueConstraint('subscriber_id', 'subscribed_id', name='subscriptions_subscriber_id_subscribed_id_key')
    )
    # ### end Alembic commands ###
