""" 

Revision ID: 22e57654570f
Revises: 148db31d6576
Create Date: 2024-04-17 11:13:28.365413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e57654570f'
down_revision: Union[str, None] = '148db31d6576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_tags', ['user_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tags', type_='unique')
    # ### end Alembic commands ###
