"""Create user model

Revision ID: 8aa3a508ecad
Revises: 
Create Date: 2024-04-09 15:58:08.938687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa3a508ecad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('second_name', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_patronymic'), 'users', ['patronymic'], unique=False)
    op.create_index(op.f('ix_users_second_name'), 'users', ['second_name'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_cost'), 'post', ['cost'], unique=False)
    op.create_index(op.f('ix_post_description'), 'post', ['description'], unique=False)
    op.create_index(op.f('ix_post_event_date'), 'post', ['event_date'], unique=False)
    op.create_index(op.f('ix_post_event_time'), 'post', ['event_time'], unique=False)
    op.create_index(op.f('ix_post_favorites_count'), 'post', ['favorites_count'], unique=False)
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_index(op.f('ix_post_location'), 'post', ['location'], unique=False)
    op.create_index(op.f('ix_post_owner_id'), 'post', ['owner_id'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descriptions', sa.String(length=2550), nullable=True),
    sa.Column('content', sa.String(length=2550), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_descriptions'), 'stories', ['descriptions'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_descriptions'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_owner_id'), table_name='post')
    op.drop_index(op.f('ix_post_location'), table_name='post')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_index(op.f('ix_post_favorites_count'), table_name='post')
    op.drop_index(op.f('ix_post_event_time'), table_name='post')
    op.drop_index(op.f('ix_post_event_date'), table_name='post')
    op.drop_index(op.f('ix_post_description'), table_name='post')
    op.drop_index(op.f('ix_post_cost'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_second_name'), table_name='users')
    op.drop_index(op.f('ix_users_patronymic'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
