""" 

Revision ID: c0610f37bd10
Revises: 22e57654570f
Create Date: 2024-04-17 11:14:47.997294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0610f37bd10'
down_revision: Union[str, None] = '22e57654570f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post_tags', ['post_id', 'tag_id'])
    op.create_unique_constraint(None, 'story_tags', ['story_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story_tags', type_='unique')
    op.drop_constraint(None, 'post_tags', type_='unique')
    # ### end Alembic commands ###
