"""complaints

Revision ID: ecda2ee9a0d1
Revises: 8098cf5a2728
Create Date: 2024-04-16 17:58:10.387141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecda2ee9a0d1'
down_revision: Union[str, None] = '8098cf5a2728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_user_id'), 'complaints_user', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_user_value'), 'complaints_user', ['value'], unique=False)
    op.create_table('complaints_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_post_id'), 'complaints_post', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_post_value'), 'complaints_post', ['value'], unique=False)
    op.create_table('complaints_story',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_story_id'), 'complaints_story', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_story_value'), 'complaints_story', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_story_value'), table_name='complaints_story')
    op.drop_index(op.f('ix_complaints_story_id'), table_name='complaints_story')
    op.drop_table('complaints_story')
    op.drop_index(op.f('ix_complaints_post_value'), table_name='complaints_post')
    op.drop_index(op.f('ix_complaints_post_id'), table_name='complaints_post')
    op.drop_table('complaints_post')
    op.drop_index(op.f('ix_complaints_user_value'), table_name='complaints_user')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints_user')
    op.drop_table('complaints_user')
    # ### end Alembic commands ###
